name: "hmg25mqtt"
version: "1.2.9"
slug: "hmg25mqtt"
description: "Connect Hame energy storage devices to Home Assistant via MQTT"
url: "https://github.com/kleimj1/hmg25mqtt"
image: "ghcr.io/kleimj1/hmg25mqtt-addon"
arch:
  - armv7
  - aarch64
  - amd64
init: false
startup: application
boot: auto
services:
  - mqtt:need
hassio_api: true
hassio_role: default
options:
  pollingInterval: 60
  responseTimeout: 30
  enableCellData: false
  enableCalibrationData: false
  enableExtraBatteryData: false
  devices:
    - deviceType: "HMA-1"
      deviceId: "device-mac-address"
schema:
  mqtt_uri: str?
  pollingInterval: int?
  responseTimeout: int?
  enableCellData: bool
  enableCalibrationData: bool
  enableExtraBatteryData: bool
  debug: bool?
  devices:
    - deviceType: str
      deviceId: str
