name: "hmg25mqtt"
description: "Connect Hame energy storage devices to Home Assistant via MQTT"
version: "1.3.1"
slug: "hmg25mqtt"
url: "https://github.com/kleimj1/hmg25mqtt"
image: "ghcr.io/kleimj1/hmg25mqtt-addon"
arch:
  - aarch64
startup: application
boot: auto
init: false
hassio_api: true
hassio_role: default
services:
  - mqtt:need
options:
  pollingInterval: 60
  responseTimeout: 30
  enableCellData: false
  enableCalibrationData: false
  enableExtraBatteryData: false
  devices:
    - deviceType: "HMA-1"
      deviceId: "device-mac-address"
schema:
  mqtt_uri: str?
  pollingInterval: int?
  responseTimeout: int?
  enableCellData: bool
  enableCalibrationData: bool
  enableExtraBatteryData: bool
  debug: bool?
  devices:
    - deviceType: str
      deviceId: str
