name: Build Image

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      context:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      platform:
        required: true
        type: string
      image-suffix:
        required: true
        type: string
      build-args:
        required: false
        type: string
        default: ""
      tags:
        required: true
        type: string
      digest-prefix:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Safe platform name
        id: safe-platform
        run: |
          SAFE_PLATFORM=$(echo "${{ inputs.platform }}" | sed 's|/|-|g')
          echo "SAFE_PLATFORM=${SAFE_PLATFORM}" >> $GITHUB_ENV

      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          platforms: ${{ inputs.platform }}
          file: ${{ inputs.dockerfile }}
          push: true
          build-args: |
            ${{ inputs.build-args }}
          tags: |
            ${{ inputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save digest
        run: |
          mkdir -p /tmp/digests
          echo "${{ steps.docker_build.outputs.digest }}" > /tmp/digests/${{ env.SAFE_PLATFORM }}

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.digest-prefix }}${{ env.SAFE_PLATFORM }}
          path: /tmp/digests/
