name: Build Image

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      context:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      platform:
        required: true
        type: string
      safe-platform:
        required: true
        type: string
      image-suffix:
        required: true
        type: string
      build-args:
        required: false
        type: string
        default: ""
      tags:
        required: true
        type: string
      digest-prefix:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platform }}
          push: true
          tags: ${{ inputs.tags }}
          build-args: |
            ${{ inputs.build-args }}
          provenance: false

      - name: Fetch digest
        run: |
          DIGEST=$(docker buildx imagetools inspect ${{ inputs.tags }} \
            | grep '^Digest:' | head -n1 | awk '{print $2}')
          echo "digest=$DIGEST" >> $GITHUB_ENV

      - name: Save digest
        run: |
          mkdir -p /tmp/digests/${{ inputs.safe-platform }}
          echo "${{ env.digest }}" > /tmp/digests/${{ inputs.safe-platform }}/digest.txt

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.digest-prefix }}${{ inputs.safe-platform }}
          path: /tmp/digests/${{ inputs.safe-platform }}/digest.txt
