name: Build Image

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      addon:
        required: true
        type: string
      arch:
        required: true
        type: string
      dockerhub:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ inputs.addon }}
          file: ./${{ inputs.addon }}/Dockerfile
          platforms: linux/${{ inputs.arch }}
          push: true
          tags: |
            ${{ inputs.dockerhub }}/${{ inputs.addon }}-${{ inputs.arch }}
          build-args: |
            ARCH=${{ inputs.arch }}
          provenance: false
