name: CI Pipeline

on:
  push:
    branches: [ main ]
    tags: [ "*.*.*" ]
  pull_request:
    branches: [ main ]

permissions:
  packages: write
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      # … euer validate-Flow bleibt unverändert …

  build:
    needs: validate
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            safe: linux-amd64
          - platform: linux/arm64
            safe: linux-arm64
          - platform: linux/arm/v7
            safe: linux-arm-v7
    uses: ./.github/workflows/build-image.yml
    with:
      registry: ghcr.io
      context: .
      dockerfile: ./Dockerfile
      platform: ${{ matrix.platform }}
      image-suffix: ""
      build-args: |
        NODE_ENV=production
      # Hier den „safe“ Namen nutzen:
      tags: ghcr.io/kleimj1/hmg25mqtt:${{ github.ref_name }}-${{ matrix.safe }}
      digest-prefix: "digest-base-"

  merge:
    needs: build
    uses: ./.github/workflows/merge-manifests.yml
    with:
      registry: ghcr.io
      image-suffix: ""
      digest-prefix: "digest-base-"

  build-addon:
    needs: validate
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            safe: linux-amd64
          - platform: linux/arm64
            safe: linux-arm64
          - platform: linux/arm/v7
            safe: linux-arm-v7
    uses: ./.github/workflows/build-image.yml
    with:
      registry: ghcr.io
      context: .
      dockerfile: ha_addon/Dockerfile
      platform: ${{ matrix.platform }}
      image-suffix: "-addon"
      build-args: |
        BUILD_FROM=ghcr.io/hassio-addons/base:14.2.2
      tags: ghcr.io/kleimj1/hmg25mqtt-addon:${{ github.ref_name }}-${{ matrix.safe }}
      digest-prefix: "digest-addon-"

  merge-addon:
    needs: build-addon
    uses: ./.github/workflows/merge-manifests.yml
    with:
      registry: ghcr.io
      image-suffix: "-addon"
      digest-prefix: "digest-addon-"
