name: Build Home Assistant Add-on

on:
  push:
    branches:
      - main
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-addon:
    name: Build Add-on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push add-on using Home Assistant Builder
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target ha_addon \
            --docker-hub ghcr.io/${{ github.repository_owner }} \
            --image hmg25mqtt-addon
