name: Build Home Assistant Add-on

on:
  push:
    branches:
      - main
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-addon:
    name: Build aarch64 Add-on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push add-on using HA builder
        run: |
          docker run --rm --privileged \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "${{ github.workspace }}:/data" \
            ghcr.io/home-assistant/builder/aarch64:latest \
              --target /data/ha_addon \
              --docker-hub ghcr.io/${{ github.repository_owner }} \
              --image hmg25mqtt-addon \
              --aarch64 \
              --addon
