name: CI Pipeline


on:
  push:
    branches: [ main ]
    tags: [ "*.*.*" ]
  pull_request:
    branches: [ main ]

permissions:
  packages: write
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm test -- --ci --reporters=default --reporters=jest-junit --forceExit --detectOpenHandles
        env:
          JEST_JUNIT_OUTPUT_DIR: ./test-results

      - name: Build TypeScript
        run: npm run build

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-node-${{ matrix.node-version }}
          path: ./test-results/junit.xml
          if-no-files-found: warn

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Check Prettier formatting
        run: |
          npx prettier --check "src/**/*.ts" || (
            echo "::warning file=Prettier::Code style issues found. Please run 'npm run format'."
            exit 0
          )

  build:
    needs: [validate, prettier]
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/arm/v7]
    uses: ./.github/workflows/build-image.yml
    with:
      registry: ghcr.io
      context: .
      dockerfile: ./Dockerfile
      platform: ${{ matrix.platform }}
      image-suffix: ""
      build-args: |
        NODE_ENV=production
      tags: |
        ghcr.io/kleimj1/hmg25mqtt:${{ github.ref_name }}-${{ matrix.platform }}
      digest-prefix: "digests-base-"

  merge:
    needs: [build]
    uses: ./.github/workflows/merge-manifests.yml
    with:
      registry: ghcr.io
      image-suffix: ""
      digest-prefix: "digests-base-"

  build-addon:
    needs: [validate, prettier]
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/arm/v7]
    uses: ./.github/workflows/build-image.yml
    with:
      registry: ghcr.io
      context: .
      dockerfile: ha_addon/Dockerfile
      platform: ${{ matrix.platform }}
      image-suffix: "-addon"
      build-args: |
        BUILD_FROM=ghcr.io/hassio-addons/base:14.2.2
      tags: |
        ghcr.io/kleimj1/hmg25mqtt-addon:${{ github.ref_name }}-${{ matrix.platform }}
      digest-prefix: "digests-addon-"

  merge-addon:
    needs: [build-addon]
    uses: ./.github/workflows/merge-manifests.yml
    with:
      registry: ghcr.io
      image-suffix: "-addon"
      digest-prefix: "digests-addon-"
