name: CI Pipeline

on:
  push:
    branches: [ main ]
    tags: [ "*.*.*" ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      changed_addons: ${{ steps.changed_addons.outputs.addons }}
      changed: ${{ steps.changed_addons.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed_files
        uses: jitterbit/get-changed-files@v1

      - name: Find add-on directories
        id: addons
        uses: home-assistant/actions/helpers/find-addons@master

      - name: Get changed add-ons
        id: changed_addons
        run: |
          declare -a changed_addons
          for addon in ${{ steps.addons.outputs.addons }}; do
            if [[ "${{ steps.changed_files.outputs.all }}" =~ $addon ]]; then
              changed_addons+=("\"${addon}\"")
            fi
          done
          changed=$(echo ${changed_addons[@]} | jq -cs .)
          echo "addons=${changed}" >> $GITHUB_ENV
          if [ "${#changed_addons[@]}" -gt 0 ]; then
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "changed=false" >> $GITHUB_ENV
          fi

  build:
    needs: init
    if: always()   # <-- Damit wird build immer ausgeführt!
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/arm/v7]
        safe:
          - linux-amd64
          - linux-arm64
          - linux-arm-v7
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Image
        uses: ./.github/workflows/build-image.yml
        with:
          registry: ghcr.io
          context: .
          dockerfile: ./Dockerfile
          platform: ${{ matrix.platform }}
          safe-platform: ${{ matrix.safe }}
          image-suffix: ""
          build-args: |
            NODE_ENV=production
          tags: |
            ghcr.io/kleimj1/hmg25mqtt:${{ github.ref_name }}-${{ matrix.safe }}
          digest-prefix: digest-base-

  merge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Merge Manifests
        uses: ./.github/workflows/merge-manifests.yml
        with:
          registry: ghcr.io
          image-suffix: ""
          digest-prefix: digest-base-
