name: Build Home Assistant Add-on

on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - main

jobs:
  build-addon:
    name: Build and Push Add-on
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Home Assistant Add-on
        uses: home-assistant/builder@2024.11.1
        with:
          args: |
            --all \
            --target ./ha_addon \
            --docker-hub ghcr.io/${{ github.repository_owner }} \
            --addon
