name: Build Home Assistant Add-on

on:
  push:
    branches: [main]
    tags: ["*.*.*"]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-addon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies and build TypeScript
        run: |
          npm ci --omit=dev
          npm run build
          mkdir -p ha_addon/dist
          cp -r dist/* ha_addon/dist/
          cp -r node_modules ha_addon/

      - name: Verify required files
        run: |
          ls -la ha_addon
          test -f ha_addon/run.sh || (echo "❌ run.sh fehlt!" && exit 1)
          test -f ha_addon/dist/index.js || (echo "❌ dist/index.js fehlt!" && exit 1)
          test -d ha_addon/node_modules || (echo "❌ node_modules fehlt!" && exit 1)

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push add-on using Home Assistant Builder
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target ha_addon \
            --docker-hub ghcr.io/${{ github.repository_owner }} \
            --image hmg25mqtt-addon
