name: CI Pipeline

on:
  push:
    branches: [ main ]
    tags: [ "*.*.*" ]
  pull_request:
    branches: [ main ]

permissions:
  packages: write
  contents: read

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.setvars.outputs.changed }}
    steps:
      - uses: actions/checkout@v4

      - name: Set outputs
        id: setvars
        run: |
          echo "changed=true" >> $GITHUB_ENV
          echo "changed=true" >> $GITHUB_OUTPUT

  build:
    needs: init
    if: needs.init.outputs.changed == 'true'
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            safe-platform: linux-amd64
          - platform: linux/arm64
            safe-platform: linux-arm64
          - platform: linux/arm/v7
            safe-platform: linux-arm-v7
    uses: ./.github/workflows/build-image.yml
    with:
      registry: ghcr.io
      context: .
      dockerfile: ./Dockerfile
      platform: ${{ matrix.platform }}
      safe-platform: ${{ matrix.safe-platform }}
      image-suffix: ""
      build-args: NODE_ENV=production
      tags: ghcr.io/kleimj1/hmg25mqtt:${{ github.ref_name }}-${{ matrix.safe-platform }}
      digest-prefix: digest-base-

  merge:
    needs: build
    uses: ./.github/workflows/merge-manifests.yml
    with:
      registry: ghcr.io
      image-suffix: ""
      digest-prefix: digest-base-
