name: CI Pipeline

on:
  push:
    branches: [ main ]
    tags: [ "*.*.*" ]
  pull_request:
    branches: [ main ]

permissions:
  packages: write
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test -- --ci --reporters=default --reporters=jest-junit
        env:
          JEST_JUNIT_OUTPUT_DIR: ./test-results

      - name: Build TypeScript
        run: npm run build

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-node-${{ matrix.node-version }}
          path: ./test-results/junit.xml
          if-no-files-found: warn

  build:
    needs: validate
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            safe: linux-amd64
          - platform: linux/arm64
            safe: linux-arm64
          - platform: linux/arm/v7
            safe: linux-arm-v7
    uses: ./.github/workflows/build-image.yml
    with:
      registry: ghcr.io
      context: .
      dockerfile: ./Dockerfile
      platform: ${{ matrix.platform }}
      image-suffix: ""
      build-args: |
        NODE_ENV=production
      tags: ghcr.io/kleimj1/hmg25mqtt:${{ github.ref_name }}-${{ matrix.safe }}
      digest-prefix: digest-base-

  merge:
    needs: build
    runs-on: ubuntu-latest
    uses: ./.github/workflows/merge-manifests.yml
    with:
      registry: ghcr.io
      image-suffix: ""
      digest-prefix: digest-base-

  build-addon:
    needs: validate
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            safe: linux-amd64
          - platform: linux/arm64
            safe: linux-arm64
          - platform: linux/arm/v7
            safe: linux-arm-v7
    uses: ./.github/workflows/build-image.yml
    with:
      registry: ghcr.io
      context: .
      dockerfile: ha_addon/Dockerfile
      platform: ${{ matrix.platform }}
      image-suffix: "-addon"
      build-args: |
        BUILD_FROM=ghcr.io/hassio-addons/base:14.2.2
      tags: ghcr.io/kleimj1/hmg25mqtt-addon:${{ github.ref_name }}-${{ matrix.safe }}
      digest-prefix: digest-addon-

  merge-addon:
    needs: build-addon
    runs-on: ubuntu-latest
    uses: ./.github/workflows/merge-manifests.yml
    with:
      registry: ghcr.io
      image-suffix: "-addon"
      digest-prefix: digest-addon-
